# action.yml
name: 'Dependencies license compliance checker'
author: 'Vitaly R. Samigullin'
description: 'Detect license names and types for Python PyPI packages or a list of licenses obtained by third-party tools'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  requirements:
    description: 'Path to requirements file(s)'
    required: false
  external:
    description: 'Path to CSV file(s) in format: `package_name,license_name[,...]`'
    required: false
  external-format:
    description: 'External file format: csv, cocoapods, gradle'
    required: false
  external-options:
    description: 'String of options map in EDN format'
    required: false
  fail:
    description: 'Return non-zero exit code if specified license type(s) found'
    required: false
  fails-only:
    description: 'Print only packages of license types specified with `fail` input.'
    required: false
  exclude:
    description: 'PCRE to exclude matching packages'
    required: false
  exclude-license:
    description: 'PCRE to exclude packages with matching license names'
    required: false
  pre:
    description: 'Include pre-release and development versions'
    required: false
  with-totals:
    description: 'Print totals for license types'
    required: false
  totals-only:
    description: 'Print only totals for license types'
    required: false
  table-headers:
    description: 'Print table headers'
    required: false
  formatter:
    description: 'Printf-style formatter string for report formatting'
    required: false
outputs:
  report:
    description: 'License check report'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.requirements }}       # ${1}
    - ${{ inputs.external }}           # ${2}
    - ${{ inputs.external-format }}    # ${3}
    - ${{ inputs.external-options }}   # ${4}
    - ${{ inputs.fail }}               # ${5}
    - ${{ inputs.fails-only }}         # ${6}
    - ${{ inputs.exclude }}            # ${7}
    - ${{ inputs.exclude-license }}    # ${8}
    - ${{ inputs.pre }}                # ${9}
    - ${{ inputs.with-totals }}        # ${10}
    - ${{ inputs.totals-only }}        # ${11}
    - ${{ inputs.table-headers }}      # ${12}
    - ${{ inputs.formatter }}          # ${13}
